# Generated by OmopViewer 0.5.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    summarise_clinical_records = FALSE,
    summarise_trend_episode = FALSE,
    summarise_trend_event = FALSE,
    summarise_person = FALSE,
    summarise_characteristics = FALSE,
    summarise_imd = FALSE,
    measurement_timings = FALSE,
    measurement_value_as_numeric = FALSE,
    measurement_value_as_concept = FALSE,
    summarise_log_file = FALSE
  )

  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |> shiny::bindEvent(input$summarise_omop_snapshot_cdm_name,
                         input$summarise_omop_snapshot_variable_name,
                         ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })
  
  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |> shiny::bindEvent(input$summarise_observation_period_cdm_name,
                         input$summarise_observation_period_observation_period_ordinal,
                         # input$summarise_observation_period_age_group,
                         # input$summarise_observation_period_sex,
                         input$summarise_observation_period_variable_name,
                         input$summarise_observation_period_estimate_name,
                         input$summarise_observation_period_name,
                         ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })
  
  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal) |>
      # omopgenerics::filterStrata(
      #   .data$age_group %in% input$summarise_observation_period_age_group,
      #   .data$sex %in% input$summarise_observation_period_sex
      # ) |>
      omopgenerics::filterSettings(.data$name_observation_period %in% input$summarise_observation_period_name)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      dplyr::filter(!(grepl("na", .data$estimate_name) | grepl("zero", .data$estimate_name))) |>
      OmopSketch::tableObservationPeriod()
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )
  getSummariseObservationPeriodTableMissing <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableMissingData()
  })
  output$summarise_observation_period_tableMissing <- gt::render_gt({
    getSummariseObservationPeriodTableMissing()
  })
  output$summarise_observation_period_tableMissing_download <- shiny::downloadHandler(
    filename = paste0("table_missing_data_observation_period.", input$summarise_observation_period_tableMissing_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTableMissing(), file)
    }
  )
  # summarise_clinical_records -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_clinical_records <- TRUE
  }) |> shiny::bindEvent(input$summarise_clinical_records_cdm_name,
                         input$summarise_clinical_records_omop_table,
                         input$summarise_clinical_records_variable_name,
                         input$summarise_clinical_records_estimate_name,
                         ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_clinical_records, {
    if (updateButtons$summarise_clinical_records == TRUE) {
      output$update_message_summarise_clinical_records <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_clinical_records <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_clinical_records, {
    updateButtons$summarise_clinical_records <- FALSE
  })
  
  ## get summarise_clinical_records data
  getSummariseClinicalRecordsData <- shiny::eventReactive(input$update_summarise_clinical_records, {
    data[["summarise_clinical_records"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_clinical_records_cdm_name,
        .data$variable_name %in% input$summarise_clinical_records_variable_name,
        .data$estimate_name %in% input$summarise_clinical_records_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_clinical_records_omop_table) 
  })
  getSummariseClinicalRecordsTable <- shiny::reactive({
    getSummariseClinicalRecordsData() |>
      dplyr::filter(!(grepl("na", .data$estimate_name) | grepl("zero", .data$estimate_name))) |>
      OmopSketch::tableClinicalRecords()
  })
  output$summarise_clinical_records_table <- gt::render_gt({
    getSummariseClinicalRecordsTable()
  })
  output$summarise_clinical_records_table_download <- shiny::downloadHandler(
    filename = paste0("table_clinical_records.", input$summarise_clinical_records_table_format),
    content = function(file) {
      gt::gtsave(getSummariseClinicalRecordsTable(), file)
    }
  )
  getSummariseClinicalRecordsTableMissing <- shiny::reactive({
    getSummariseClinicalRecordsData() |>
      OmopSketch::tableMissingData()
  })
  output$summarise_clinical_records_tableMissing <- gt::render_gt({
    getSummariseClinicalRecordsTableMissing()
  })
  output$summarise_clinical_records_tableMissing_download <- shiny::downloadHandler(
    filename = paste0("table_missing_data_clinical_records.", input$summarise_clinical_records_tableMissing_format),
    content = function(file) {
      gt::gtsave(getSummariseClinicalRecordsTableMissing(), file)
    }
  )
  # summarise_person -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_person <- TRUE
  }) |> shiny::bindEvent(input$summarise_person_cdm_name,
                         input$summarise_person_variable_name,
                         input$summarise_person_estimate_name,
                         ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_person, {
    if (updateButtons$summarise_person == TRUE) {
      output$update_message_summarise_person <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_person <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_person, {
    updateButtons$summarise_person <- FALSE
  })
  
  ## get summarise_person data
  getSummarisePersonData <- shiny::eventReactive(input$update_summarise_person, {
    data[["summarise_person"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_person_cdm_name,
        .data$variable_name %in% input$summarise_person_variable_name,
        .data$estimate_name %in% input$summarise_person_estimate_name
      )
  })
  getSummarisePersonTable <- shiny::reactive({
    getSummarisePersonData() |>
      OmopSketch::tablePerson()
  })
  output$summarise_person_table <- gt::render_gt({
    getSummarisePersonTable()
  })
  output$summarise_person_table_download <- shiny::downloadHandler(
    filename = paste0("table_person.", input$summarise_person_table_format),
    content = function(file) {
      gt::gtsave(getSummarisePersonTable(), file)
    }
  )
  getSummarisePersonPlot <- shiny::reactive({
    getSummarisePersonData() |>
      OmopSketch::plotPerson(
        variableName = input$summarise_person_plot_variable
      )
  })
  output$summarise_person_plot <- shiny::renderUI({
    x <- getSummarisePersonPlot()
    renderInteractivePlot(x, input$summarise_person_plot_interactive)
  })
  output$summarise_person_plot_download <- shiny::downloadHandler(
    filename = "plot_person.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummarisePersonPlot(),
        width = as.numeric(input$summarise_person_plot_width),
        height = as.numeric(input$summarise_person_plot_height),
        units = input$summarise_person_plot_units,
        dpi = as.numeric(input$summarise_person_plot_dpi)
      )
    }
  )
  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |> shiny::bindEvent(input$summarise_characteristics_cdm_name,
                         input$summarise_characteristics_cohort_name,
                         # input$summarise_characteristics_sex,
                         input$summarise_characteristics_variable_name,
                         input$summarise_characteristics_estimate_name,
                         ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })
  
  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) 
    # |>
    #   omopgenerics::filterStrata(.data$sex %in% input$summarise_characteristics_sex)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # summarise_trend_episode -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_trend_episode <- TRUE
  }) |> shiny::bindEvent(input$summarise_trend_episode_cdm_name,
                         input$summarise_trend_episode_omop_table,
                         # input$summarise_trend_episode_age_group,
                         # input$summarise_trend_episode_sex,
                         input$summarise_trend_episode_time_interval,
                         input$summarise_trend_episode_name_observation_period,
                         # input$summarise_trend_episode_variable_name,
                         # input$summarise_trend_episode_estimate_name,
                         ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_trend_episode, {
    if (updateButtons$summarise_trend_episode == TRUE) {
      output$update_message_summarise_trend_episode <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_trend_episode <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_trend_episode, {
    updateButtons$summarise_trend_episode <- FALSE
  })
  
  ## get summarise_trend_episode data
  getSummariseTrendEpisodeData <- shiny::eventReactive(input$update_summarise_trend_episode, {
    data[["summarise_trend_episode"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_trend_episode_cdm_name
        # ,
        # .data$variable_name %in% input$summarise_trend_episode_variable_name,
        # .data$estimate_name %in% input$summarise_trend_episode_estimate_name
      ) |>
      # omopgenerics::filterStrata(
      #   .data$age_group %in% input$summarise_trend_episode_age_group,
      #   .data$sex %in% input$summarise_trend_episode_sex
      # ) |>
      omopgenerics::filterAdditional(.data$time_interval %in% input$summarise_trend_episode_time_interval) |>
      omopgenerics::filterSettings(
        .data$name_observation_period %in% input$summarise_trend_episode_name_observation_period)
  })
  getSummariseTrendEpisodeTable <- shiny::reactive({
    getSummariseTrendEpisodeData() |>
      OmopSketch::tableTrend(type = "reactable")
  })
  output$summarise_trend_episode_table <- reactable::renderReactable({
    getSummariseTrendEpisodeTable()
  })
  output$summarise_trend_episode_table_download <- shiny::downloadHandler(
    filename = "trends.csv",
    content = function(file) {
      getSummariseTrendEpisodeTable() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseTrendEpisodePlot <- shiny::reactive({
    getSummariseTrendEpisodeData() |>
      OmopSketch::plotTrend(
        facet = input$summarise_trend_episode_plot_facet,
        colour = input$summarise_trend_episode_plot_colour
      )
  })
  output$summarise_trend_episode_plot <- shiny::renderUI({
    x <- getSummariseTrendEpisodePlot()
    renderInteractivePlot(x, input$summarise_trend_episode_plot_interactive)
  })
  output$summarise_trend_episode_plot_download <- shiny::downloadHandler(
    filename = "plot_trend.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseTrendEpisodePlot(),
        width = as.numeric(input$summarise_trend_episode_plot_width),
        height = as.numeric(input$summarise_trend_episode_plot_height),
        units = input$summarise_trend_episode_plot_units,
        dpi = as.numeric(input$summarise_trend_episode_plot_dpi)
      )
    }
  )
  # summarise_trend_event -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_trend_event <- TRUE
  }) |> shiny::bindEvent(input$summarise_trend_event_cdm_name,
                         input$summarise_trend_event_omop_table,
                         # input$summarise_trend_event_age_group,
                         # input$summarise_trend_event_sex,
                         input$summarise_trend_event_in_observation,
                         input$summarise_trend_event_variable_name,
                         input$summarise_trend_event_estimate_name,
                         input$summarise_trend_event_time_interval,
                         ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_trend_event, {
    if (updateButtons$summarise_trend_event == TRUE) {
      output$update_message_summarise_trend_event <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_trend_event <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_trend_event, {
    updateButtons$summarise_trend_event <- FALSE
  })
  
  ## get summarise_trend_event data
  getSummariseTrendEventData <- shiny::eventReactive(input$update_summarise_trend_event, {
    data[["summarise_trend_event"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_trend_event_cdm_name,
        .data$variable_name %in% input$summarise_trend_event_variable_name,
        .data$estimate_name %in% input$summarise_trend_event_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_trend_event_omop_table) |>
      omopgenerics::filterStrata(
        # .data$age_group %in% input$summarise_trend_event_age_group,
        # .data$sex %in% input$summarise_trend_event_sex,
        .data$in_observation %in% input$summarise_trend_event_in_observation
      ) |>
      omopgenerics::filterAdditional(.data$time_interval %in% input$summarise_trend_event_time_interval)
  })
  getSummariseTrendEventTable <- shiny::reactive({
    getSummariseTrendEventData() |>
      OmopSketch::tableTrend(type = "reactable")
  })
  output$summarise_trend_event_table <- reactable::renderReactable({
    getSummariseTrendEventTable()
  })
  output$summarise_trend_event_table_download <- shiny::downloadHandler(
    filename = "trends.csv",
    content = function(file) {
      getSummariseTrendEventTable() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseTrendEventPlot <- shiny::reactive({
    getSummariseTrendEventData() |>
      OmopSketch::plotTrend(
        facet = input$summarise_trend_event_plot_facet,
        colour = input$summarise_trend_event_plot_colour
      )
  })
  output$summarise_trend_event_plot <- shiny::renderUI({
    x <- getSummariseTrendEventPlot()
    renderInteractivePlot(x, input$summarise_trend_event_plot_interactive)
  })
  output$summarise_trend_event_plot_download <- shiny::downloadHandler(
    filename = "plot_trend.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseTrendEventPlot(),
        width = as.numeric(input$summarise_trend_event_plot_width),
        height = as.numeric(input$summarise_trend_event_plot_height),
        units = input$summarise_trend_event_plot_units,
        dpi = as.numeric(input$summarise_trend_event_plot_dpi)
      )
    }
  )

  # summarise_imd -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_imd <- TRUE
  }) |> shiny::bindEvent(input$summarise_imd_cdm_name,
    input$summarise_imd_variable_name,
    input$summarise_imd_estimate_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_imd, {
    if (updateButtons$summarise_imd == TRUE) {
      output$update_message_summarise_imd <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_imd <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_imd, {
    updateButtons$summarise_imd <- FALSE
  })

  ## get summarise_imd data
  getSummariseImdData <- shiny::eventReactive(input$update_summarise_imd, {
    data[["summarise_imd"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_imd_cdm_name,
        .data$variable_name %in% input$summarise_imd_variable_name,
        .data$estimate_name %in% input$summarise_imd_estimate_name
      )
  })
  getSummariseImdTidy <- shiny::reactive({
    tidyDT(getSummariseImdData(), input$summarise_imd_tidy_columns, input$summarise_imd_tidy_pivot_estimates)
  })
  output$summarise_imd_tidy <- DT::renderDT({
    getSummariseImdTidy()
  })
  output$summarise_imd_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseImdData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseImdTable <- shiny::reactive({
    getSummariseImdData() |>
      simpleTable(
        header = input$summarise_imd_table_header,
        group = input$summarise_imd_table_group_column,
        hide = input$summarise_imd_table_hide
      )
  })
  output$summarise_imd_table <- gt::render_gt({
    getSummariseImdTable()
  })
  output$summarise_imd_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_imd_table_format),
    content = function(file) {
      gt::gtsave(getSummariseImdTable(), file)
    }
  )
  # measurement_timings -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$measurement_timings <- TRUE
  }) |> shiny::bindEvent(input$measurement_timings_cdm_name,
    input$measurement_timings_codelist_name,
    input$measurement_timings_variable_name,
    input$measurement_timings_estimate_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$measurement_timings, {
    if (updateButtons$measurement_timings == TRUE) {
      output$update_message_measurement_timings <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_measurement_timings <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_measurement_timings, {
    updateButtons$measurement_timings <- FALSE
  })

  ## get measurement_timings data
  getMeasurementTimingsData <- shiny::eventReactive(input$update_measurement_timings, {
    data[["measurement_timings"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$measurement_timings_cdm_name,
        .data$variable_name %in% input$measurement_timings_variable_name,
        .data$estimate_name %in% input$measurement_timings_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$codelist_name %in% input$measurement_timings_codelist_name) 
  })

  getMeasurementTimingsTable <- shiny::reactive({
    getMeasurementTimingsData() |>
      MeasurementDiagnostics::tableMeasurementTimings(
        type = "gt",
        header = input$measurement_timings_table_header,
        groupColumn = input$measurement_timings_table_group_column,
        settingsColumn = character(),
        hide = input$measurement_timings_table_hide,
        style = NULL,
        .options = list()
      )
  })
  output$measurement_timings_table <- gt::render_gt({
    getMeasurementTimingsTable()
  })
  output$measurement_timings_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$measurement_timings_table_format),
    content = function(file) {
      gt::gtsave(getMeasurementTimingsTable(), file)
    }
  )
  
  getMeasurementTimingsPlot <- shiny::reactive({
    getMeasurementTimingsData() |>
      MeasurementDiagnostics::plotMeasurementTimings(
        y = input$measurement_timings_plot_y,
        plotType = input$measurement_timings_plot_type,
        timeScale = input$measurement_timings_plot_time_scale,
        facet = input$measurement_timings_plot_facet,
        colour = input$measurement_timings_plot_colour
      )
  })
  output$measurement_timings_plot <- shiny::renderUI({
    x <- getMeasurementTimingsPlot()
    renderInteractivePlot(x, input$measurement_timings_plot_interactive)
  })
  output$measurement_timings_plot_download <- shiny::downloadHandler(
    filename = "plot_measurement_timings.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getMeasurementTimingsPlot(),
        width = as.numeric(input$measurement_timings_plot_width),
        height = as.numeric(input$measurement_timings_plot_height),
        units = input$measurement_timings_plot_units,
        dpi = as.numeric(input$measurement_timings_plot_dpi)
      )
    }
  )
  
  
  
  # measurement_value_as_numeric -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$measurement_value_as_numeric <- TRUE
  }) |> shiny::bindEvent(input$measurement_value_as_numeric_cdm_name,
    input$measurement_value_as_numeric_codelist_name,
    input$measurement_value_as_numeric_concept_name,
    input$measurement_value_as_numeric_unit_concept_name,
    input$measurement_value_as_numeric_concept_id,
    input$measurement_value_as_numeric_unit_concept_id,
    input$measurement_value_as_numeric_domain_id,
    input$measurement_value_as_numeric_variable_name,
    input$measurement_value_as_numeric_estimate_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$measurement_value_as_numeric, {
    if (updateButtons$measurement_value_as_numeric == TRUE) {
      output$update_message_measurement_value_as_numeric <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_measurement_value_as_numeric <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_measurement_value_as_numeric, {
    updateButtons$measurement_value_as_numeric <- FALSE
  })

  ## get measurement_value_as_numeric data
  getMeasurementValueAsNumericData <- shiny::eventReactive(input$update_measurement_value_as_numeric, {
    data[["measurement_value_as_numeric"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$measurement_value_as_numeric_cdm_name,
        .data$variable_name %in% input$measurement_value_as_numeric_variable_name,
        .data$estimate_name %in% input$measurement_value_as_numeric_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$codelist_name %in% input$measurement_value_as_numeric_codelist_name,
        .data$concept_name %in% input$measurement_value_as_numeric_concept_name,
        .data$unit_concept_name %in% input$measurement_value_as_numeric_unit_concept_name
      ) |>
      omopgenerics::filterAdditional(
        .data$concept_id %in% input$measurement_value_as_numeric_concept_id,
        .data$unit_concept_id %in% input$measurement_value_as_numeric_unit_concept_id,
        .data$domain_id %in% input$measurement_value_as_numeric_domain_id
      ) 
  })

  getMeasurementValueAsNumericTable <- shiny::reactive({
    getMeasurementValueAsNumericData() |>
      MeasurementDiagnostics::tableMeasurementValueAsNumeric(
        type = "gt",
        header = input$measurement_value_as_numeric_table_header,
        groupColumn = input$measurement_value_as_numeric_table_group_column,
        settingsColumn = character(),
        hide = input$measurement_value_as_numeric_table_hide,
        style = NULL,
        .options = list()
      )
  })
  output$measurement_value_as_numeric_table <- gt::render_gt({
    getMeasurementValueAsNumericTable()
  })
  output$measurement_value_as_numeric_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$measurement_value_as_numeric_table_format),
    content = function(file) {
      gt::gtsave(getMeasurementValueAsNumericTable(), file)
    }
  )
  
  getMeasurementValueAsNumericPlot <- shiny::reactive({
    getMeasurementValueAsNumericData() |>
      MeasurementDiagnostics::plotMeasurementValueAsNumeric(
        x = input$measurement_value_as_numeric_plot_x,
        plotType = input$measurement_value_as_numeric_plot_type,
        facet = input$measurement_value_as_numeric_plot_facet,
        colour = input$measurement_value_as_numeric_plot_colour
      )
  })
  output$measurement_value_as_numeric_plot <- shiny::renderUI({
    x <- getMeasurementValueAsNumericPlot()
    renderInteractivePlot(x, input$measurement_value_as_numeric_plot_interactive)
  })
  output$measurement_value_as_numeric_plot_download <- shiny::downloadHandler(
    filename = "plot_measurement_value_as_numeric.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getMeasurementValueAsNumericPlot(),
        width = as.numeric(input$measurement_value_as_numeric_plot_width),
        height = as.numeric(input$measurement_value_as_numeric_plot_height),
        units = input$measurement_value_as_numeric_plot_units,
        dpi = as.numeric(input$measurement_value_as_numeric_plot_dpi)
      )
    }
  )
  
  
  # measurement_value_as_concept -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$measurement_value_as_concept <- TRUE
  }) |> shiny::bindEvent(input$measurement_value_as_concept_cdm_name,
    input$measurement_value_as_concept_codelist_name,
    input$measurement_value_as_concept_concept_name,
    input$measurement_value_as_concept_concept_id,
    input$measurement_value_as_concept_value_as_concept_id,
    input$measurement_value_as_concept_domain_id,
    input$measurement_value_as_concept_variable_name,
    input$measurement_value_as_concept_estimate_name,
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$measurement_value_as_concept, {
    if (updateButtons$measurement_value_as_concept == TRUE) {
      output$update_message_measurement_value_as_concept <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_measurement_value_as_concept <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_measurement_value_as_concept, {
    updateButtons$measurement_value_as_concept <- FALSE
  })

  ## get measurement_value_as_concept data
  getMeasurementValueAsConceptData <- shiny::eventReactive(input$update_measurement_value_as_concept, {
    data[["measurement_value_as_concept"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$measurement_value_as_concept_cdm_name,
        .data$variable_name %in% input$measurement_value_as_concept_variable_name,
        .data$estimate_name %in% input$measurement_value_as_concept_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$codelist_name %in% input$measurement_value_as_concept_codelist_name,
        .data$concept_name %in% input$measurement_value_as_concept_concept_name
      ) |>
      omopgenerics::filterAdditional(
        .data$concept_id %in% input$measurement_value_as_concept_concept_id,
        .data$value_as_concept_id %in% input$measurement_value_as_concept_value_as_concept_id,
        .data$domain_id %in% input$measurement_value_as_concept_domain_id
      ) 
  })

  getMeasurementValueAsConceptTable <- shiny::reactive({
    getMeasurementValueAsConceptData() |>
      MeasurementDiagnostics::tableMeasurementValueAsConcept(
        type = "gt",
        header = input$measurement_value_as_concept_table_header,
        groupColumn = input$measurement_value_as_concept_table_group_column,
        settingsColumn = character(),
        hide = input$measurement_value_as_concept_table_hide,
        style = NULL,
        .options = list()
      )
  })
  output$measurement_value_as_concept_table <- gt::render_gt({
    getMeasurementValueAsConceptTable()
  })
  output$measurement_value_as_concept_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$measurement_value_as_concept_table_format),
    content = function(file) {
      gt::gtsave(getMeasurementValueAsConceptTable(), file)
    }
  )
  getMeasurementValueAsConceptPlot <- shiny::reactive({
    getMeasurementValueAsConceptData() |>
      MeasurementDiagnostics::plotMeasurementValueAsConcept(
        x = input$measurement_value_as_concept_plot_x,
        y = input$measurement_value_as_concept_plot_y,
        facet = input$measurement_value_as_concept_plot_facet,
        colour = input$measurement_value_as_concept_plot_colour
      )
  })
  output$measurement_value_as_concept_plot <- shiny::renderUI({
    x <- getMeasurementValueAsConceptPlot()
    renderInteractivePlot(x, input$measurement_value_as_concept_plot_interactive)
  })
  output$measurement_value_as_concept_plot_download <- shiny::downloadHandler(
    filename = "plot_measurement_value_as_concept.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getMeasurementValueAsConceptPlot(),
        width = as.numeric(input$measurement_value_as_concept_plot_width),
        height = as.numeric(input$measurement_value_as_concept_plot_height),
        units = input$measurement_value_as_concept_plot_units,
        dpi = as.numeric(input$measurement_value_as_concept_plot_dpi)
      )
    }
  )
  
  
  
  
}